In [13]:
import pandas as pd
import json
import numpy as np

In [14]:
df = pd.read_csv('exo-archive.csv')
df.head()

,pl_name,hostname,sy_snum,sy_pnum,discoverymethod,disc_year,disc_facility,pl_controv_flag,pl_orbper,pl_orbpererr1,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
0,11 Com b,11 Com,2,1,Radial Velocity,2007,Xinglong Station,0,323.21000,0.06000,...,-1.9238,4.72307,0.023,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848
1,11 UMi b,11 UMi,1,1,Radial Velocity,2009,Thueringer Landessternwarte Tautenburg,0,516.21997,3.20000,...,-1.9765,5.01300,0.005,-0.005,1.939,0.270,-0.270,4.56216,0.003903,-0.003903
2,14 And b,14 And,1,1,Radial Velocity,2008,Okayama Astrophysical Observatory,0,186.76000,0.11000,...,-0.7140,5.23133,0.023,-0.023,2.331,0.240,-0.240,4.91781,0.002826,-0.002826
3,14 Her b,14 Her,1,2,Radial Velocity,2002,W. M. Keck Observatory,0,1765.03890,1.67709,...,-0.0073,6.61935,0.023,-0.023,4.714,0.016,-0.016,6.38300,0.000351,-0.000351
4,16 Cyg B b,16 Cyg B,3,1,Radial Velocity,1996,Multiple Observatories,0,798.50000,1.00000,...,-0.0111,6.21500,0.016,-0.016,4.651,0.016,-0.016,6.06428,0.000603,-0.000603

In [15]:
df['dec'], df['ra']

(0       17.793252
 1       71.823943
 2       39.235837
 3       43.816362
 4       50.516824
           ...
 5760    41.403815
 5761    41.403815
 5762    41.403815
 5763    -0.823564
 5764     8.461105
 Name: dec, Length: 5765, dtype: float64,
 0       185.178779
 1       229.274595
 2       352.824150
 3       242.602101
 4       295.465642
            ...
 5760     24.198353
 5761     24.198353
 5762     24.198353
 5763    174.237219
 5764    298.562449
 Name: ra, Length: 5765, dtype: float64)

In [16]:
df['dec_radians'] = df['dec']*np.pi/180
df['ra_radians'] = np.pi/2 - df['ra']*np.pi/180

In [17]:
df['dec_radians']

0       0.310551
1       1.253564
2       0.684795
3       0.764740
4       0.881685
          ...
5760    0.722633
5761    0.722633
5762    0.722633
5763   -0.014374
5764    0.147674
Name: dec_radians, Length: 5765, dtype: float64

In [18]:
df.to_json('exoplanets.json')